# Generated by Django 3.1.7 on 2021-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okul',
            name='baslik',
            field=models.CharField(max_length=120, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='okul',
            name='metin',
            field=models.TextField(verbose_name='Metin'),
        ),
        migrations.AlterField(
            model_name='okul',
            name='yayinlanmaTarihi',
            field=models.DateTimeField(verbose_name='Yayınlanma Tarihi'),
        ),
    ]
